### ISSUE TITLE
 Mining stopped (time limit reached) ?

### ISSUE THREAD

**Issue by doublelin15** [ianjjohnson/arulesCBA#18]
When I using function CBA
there have a Warning message
"In apriori(ds.mat, parameter = parameter, appearance = list(rhs = levels(rightHand),  :
  Mining stopped (time limit reached). Only patterns up to a length of 2 returned!"

and using code

CBA(Outcome ~ ., da, supp = 0.001, conf=0.5, verbose = TRUE, parameter=c(maxtime=0))

also have same message
what happen about this?

**Comment by ianjjohnson** [comment]
This warning means that your timeout value for apriori is too short. This is a warning from the internal call to arules::apriori and can be eliminated by passing a larger maxtime to apriori.

However, I would warn you that the CBA algorithm is generally not used with such dramatically low support thresholds. Consider increasing that threshold, if possible.

**Comment by ianjjohnson** [comment]
Use a non-zero max-time. Check the apriori interface from github.com/mhahsler/arules to see if they specify that maxtime=0 means no time limit. For practical purposes, it is somewhat unusual to use an infinite time limit, as you will consume too much RAM when mining rulesets that are excessively large.
