### ISSUE TITLE
Allow fuller passing of parameters from CBA to apriori

### ISSUE THREAD

**Issue by noamross** [ianjjohnson/arulesCBA#19]
Currently, the `parameters` list passed to `CBA()` doesn't get passed in full to `apriori`, so parameters like `maxlen` aren't honored.  Is there a reason for this?

I've already partially implemented allowing more parameters to be passed on a fork as I need this for a project: https://github.com/noamross/arulesCBA/commit/fa773d1e26ebb6c96d5e60b7c36790962dfb140a . I'd be happy to go through and make sure it's consistent throughout the different functions in the package and file a PR if you are interested

**Comment by ianjjohnson** [comment]
Thanks for the suggestion!

The original CBA algorithm's paper is pretty clear about only using support, confidence, and lift thresholds for rule mining, so we deliberately avoid letting people pass more parameters to apriori where possible.

In special situations, to get around this, some other parts of the API like cba_ruleset allow for more fine-grained control. So we'll keep it as-is for now.

Thanks again, and good luck with your project!
