### ISSUE TITLE
Error in CBA.internal:  trying to get slot "i" from an object

### ISSUE THREAD

**Issue by william-vw** [ianjjohnson/arulesCBA#23]
Hi all,

I'm having trouble getting a very simple example to work. 

CSV code:
 ```
H1,H2,H3,H4,H5,H6,H7,H8,h9,H10,C
,,,,,,,0.1,,,C1
,,,,,,,0.1,,,C2
```

R code:
```
rf.data <- read.csv("/csv/path/here", sep=""), encoding="UTF-8")
rf.cba <- CBA(C ~ ., data = rf.data, supp = 0.05, conf = 0.9)
```

This code raises the following exception: 
```
Error in CBA.internal(formula, data, method = "CBA", support = support,  : 
  trying to get slot "i" from an object of a basic class ("logical") with no slots
```

The data is quite sparse - perhaps that's related to the error?

Thanks,

William

**Comment by ianjjohnson** [comment]
Do you have missing data in numerical columns? (Columns that have to be discretized). 

That could be the issue. 

Ian

**Comment by william-vw** [comment]
Yes, there's quite some missing numerical data in there, as shown in the CSV snippet. The data is very sparse.

**Comment by ianjjohnson** [comment]
arulesCBA’s automatic discretization doesn’t support missing values, so you’ll have to either impute those values or manually discretize your numeric columns. 

Ian

**Comment by william-vw** [comment]
Ok, thanks.

**Comment by mhahsler** [comment]
There are a few things going on here. Batches are now on GitHub.

* I have now added a check if no rules are mined. Now the code stops with an error message. @ianjjohnson Maybe you want to change that to a warning and return a classifier that only has a default class.
* Matrix seems to convert sparse matrices to dense matrices for !. Most of the time spares & dense -> sparse, but sometimes not. The code makes now sure that the matrix is always sparse.

The GitHub version should now work with @william-vw's data as expected.

-Michael

**Comment by william-vw** [comment]
FYI,  I can confirm that I'm getting an appropriate error when running the latest GitHub version:

`Error in CBA.internal(formula, data, method = "CBA", support = support,  :    No rules found! Reduce support or confidence.`

Thanks

**Comment by mhahsler** [comment]
Yes. This is correct. I set support and confidence to 0 and got 2 rules. That did not create a good classifier, but you need way more data...

**Comment by william-vw** [comment]
For sure - I just included a small snippet of the datasets. Nevertheless, the complete dataset is very sparse.
