### ISSUE TITLE
Function to retrieve the rule(s) used to predict the class

### ISSUE THREAD

**Issue by frequena** [ianjjohnson/arulesCBA#24]
Once that you have your model ready and use it to predict the class, is there any way to find which rule (s) has been used to define the predicted class?

**Comment by ianjjohnson** [comment]
You can access the rules from a model using the `rules` function. 

There’s information about usage in the documentation.

**Comment by ianjjohnson** [comment]
Reading your question again, perhaps you’re asking if there is a method that can determine which rule specifically matched a particular row. 

`is.subset(lhs(rules(model)), testingRow)` will give you a list of Booleans representing which rules matched the row. You’ll have to make sure the row has been correctly discredited prior do calling this.
