### ISSUE TITLE
`pruning` is not necessary when the user have its own pruning method

### ISSUE THREAD

**Issue by DouglasMesquita** [ianjjohnson/arulesCBA#30]
# Description

Currently, `pruning` is mandatory in the `CBA` function. However, I would like to have the freedom to implement my own pruning method before using CBA. In this case, I would like to skip the pruning step (M1 or M2).

# How to reproduce the issue
```
data("iris")
formula <- Species ~ .

trans <- prepareTransactions(formula = formula, data = iris)
rulebase <- mineCARs(
  formula = Species ~ .,
  transactions = trans,
  supp = 0.05,
  conf = 0.9
)
n_rules <- length(rulebase)

cba_no_pruning <- CBA(formula, iris, supp = 0.05, conf = 0.9,)
```

In this case, `length(rules(cba_no_pruning)) != n_rules` since the `M1` pruning approach was applied.

**Comment by mhahsler** [comment]
If you modify the pruning method then the resulting algorithm is not the original CBA algorithm (by Liu, et al. (1998)) anymore. You can create a new classifier using the same classification method as CBA but using your own, already pruned, rule base using `CBA_ruleset()`.
