### ISSUE TITLE
`method`, `weights`, `best_k` as prediction's parameters instead of classifiers' parameters

### ISSUE THREAD

**Issue by DouglasMesquita** [ianjjohnson/arulesCBA#32]
# Description

In believe, `method`, `weights` and, `best_k` are parameters for prediction and not for classification. To make it clear, I think the user should be able to perform all of these actions for the very same classifier object:

```
predict(classifier, data, type = "score", method = "majority", weights = NULL)
predict(classifier, data, type = "score", method = "majority", weights = "lift", best_k = NULL)
predict(classifier, data, type = "score", method = "majority", weights = "lift", best_k = 4)
predict(classifier, data, type = "score", method = "weighted", weights = "lift")
predict(classifier, data, type = "score", method = "weighted", weights = "lift", best_k = 4)
predict(classifier, data, type = "score", method = "logit", weights = "lift", best_k = 4)
predict(classifier, data, type = "class", method = "first")
```

In this case, the parameters `method`, `weights`, `best_k` should be removed from the classifier's functions as well as from the classes' structures. These parameters should appear in the `predict` function instead.

I know that it is possible to change the `method` by assigning a different one to the `classifier_obj$method`, but I think that it is not intuitive.

**Comment by mhahsler** [comment]
This is a good idea but different methods require different preprocessing of the rules. It is an inherent property of the classifier and not the prediction process.  Therefore, we chose to make changing the method not part of the interface. 

Regards,
Michael
